### ISSUE TITLE
Check if components and bindings are set

### ISSUE THREAD

**Issue by jirihelmich** [tobice/d3-ldvm-pipeline#3]
When initializing the component, it happens that data.components and data.bindings is undefined. Throws an error since .map is invoked with no check.

**Comment by tobice** [comment]
Okay. What should be the desired behaviour? Should it throw a more descriptive error (i. e. it's considered an invalid input) or just ignore it and perhaps replace the `undefined` value with empty arrays and simply render empty visualization?

**Comment by jirihelmich** [comment]
It should probably just silently do nothing.
Wed 2 Sep 2015 v 18:36 odesílatel Tobiáš Potoček notifications@github.com
napsal:

**Comment by tobice** [comment]
Fixed by c5b95d526e. Let me know if this is robust enough.
